In [1]:
import pandas as pd
import os

In [2]:
baseFile = "2014_Financial_Data"

In [3]:
os.getcwd()

'C:\\Users\\hchapman\\Desktop\\ML\\Final DS Project'

In [4]:
allFilePaths = []

for i in range(4, 9):
    #get year in format used in file name
    year = i
      
    #create filename dynamically
    subFolder = "Data_2/"
    fileName = f"{subFolder}201{year}_Financial_Data.csv"
    allFilePaths.append(fileName)
    
#Print all file paths
allFilePaths

['Data_2/2014_Financial_Data.csv',
 'Data_2/2015_Financial_Data.csv',
 'Data_2/2016_Financial_Data.csv',
 'Data_2/2017_Financial_Data.csv',
 'Data_2/2018_Financial_Data.csv']

In [5]:
df = pd.DataFrame()
year_column = 2014
for path in allFilePaths:
    loop_df = pd.read_csv(path)
    loop_df = loop_df.rename(columns={'Unnamed: 0': 'Ticker'})
    loop_df['Year'] = year_column
    df = df.append(loop_df)
    year_column += 1
df.info()

C:\Users\hchapman\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22077 entries, 0 to 4391
Columns: 230 entries, 10Y Dividend per Share Growth (per Share) to totalDebtToCapitalization
dtypes: float64(226), int64(2), object(2)
memory usage: 38.9+ MB

In [6]:
len(df)

22077

In [7]:
df.head()

,10Y Dividend per Share Growth (per Share),10Y Net Income Growth (per Share),10Y Operating CF Growth (per Share),10Y Revenue Growth (per Share),10Y Shareholders Equity Growth (per Share),2015 PRICE VAR [%],2016 PRICE VAR [%],2017 PRICE VAR [%],2018 PRICE VAR [%],2019 PRICE VAR [%],...,priceToBookRatio,priceToFreeCashFlowsRatio,priceToOperatingCashFlowsRatio,priceToSalesRatio,quickRatio,returnOnAssets,returnOnCapitalEmployed,returnOnEquity,shortTermCoverageRatios,totalDebtToCapitalization
0,0.1013,0.0603,0.0355,0.0323,0.1442,-9.323276,NaN,NaN,NaN,NaN,...,0.0000,21.0348,15.2358,2.8583,0.506197,0.5765,0.0753,0.1664,0.894400,0.336047
1,NaN,NaN,NaN,NaN,NaN,-25.512193,NaN,NaN,NaN,NaN,...,NaN,1.3589,NaN,0.0443,0.849993,0.0403,0.0000,0.3294,NaN,0.601485
2,0.0000,0.2272,0.0889,0.1027,0.0676,33.118297,NaN,NaN,NaN,NaN,...,7.0982,14.6302,5.1147,0.1858,0.141709,0.1011,0.0859,0.2821,2.156307,0.677489
3,0.0000,0.0480,0.0513,-0.0195,0.0000,2.752291,NaN,NaN,NaN,NaN,...,0.0000,17.2736,9.0589,0.2491,0.436885,0.0668,0.1062,-0.1180,14.276772,1.580139
4,0.1092,0.0776,0.0782,0.0704,0.0427,12.897715,NaN,NaN,NaN,NaN,...,0.0000,17.6902,13.1169,1.8610,0.433465,0.6265,0.1041,0.2792,1.075647,0.573463

In [8]:
df.columns

Index(['10Y Dividend per Share Growth (per Share)',
       '10Y Net Income Growth (per Share)',
       '10Y Operating CF Growth (per Share)', '10Y Revenue Growth (per Share)',
       '10Y Shareholders Equity Growth (per Share)', '2015 PRICE VAR [%]',
       '2016 PRICE VAR [%]', '2017 PRICE VAR [%]', '2018 PRICE VAR [%]',
       '2019 PRICE VAR [%]',
       ...
       'priceToBookRatio', 'priceToFreeCashFlowsRatio',
       'priceToOperatingCashFlowsRatio', 'priceToSalesRatio', 'quickRatio',
       'returnOnAssets', 'returnOnCapitalEmployed', 'returnOnEquity',
       'shortTermCoverageRatios', 'totalDebtToCapitalization'],
      dtype='object', length=230)

In [9]:
df.to_csv("Data_2/combined_10k.csv", index=False)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22077 entries, 0 to 4391
Columns: 230 entries, 10Y Dividend per Share Growth (per Share) to totalDebtToCapitalization
dtypes: float64(226), int64(2), object(2)
memory usage: 38.9+ MB

In [11]:
df.tail()

,10Y Dividend per Share Growth (per Share),10Y Net Income Growth (per Share),10Y Operating CF Growth (per Share),10Y Revenue Growth (per Share),10Y Shareholders Equity Growth (per Share),2015 PRICE VAR [%],2016 PRICE VAR [%],2017 PRICE VAR [%],2018 PRICE VAR [%],2019 PRICE VAR [%],...,priceToBookRatio,priceToFreeCashFlowsRatio,priceToOperatingCashFlowsRatio,priceToSalesRatio,quickRatio,returnOnAssets,returnOnCapitalEmployed,returnOnEquity,shortTermCoverageRatios,totalDebtToCapitalization
4387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-90.962099,...,1.7686,0.0000,-108.4577,0.0000,0.002142,NaN,NaN,-0.0800,-0.361092,0.406512
4388,0.0,0.0,0.0,-0.3488,-0.4288,NaN,NaN,NaN,NaN,-77.922077,...,1.4604,0.0000,-0.9506,14.9666,3.815356,-0.8423,-0.9562,-1.6093,-10.372038,0.531530
4389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-17.834400,...,NaN,0.0000,NaN,0.7619,1.189722,0.2228,0.1269,0.1895,-0.115980,0.342208
4390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-73.520000,...,32.4576,0.0000,-10.4597,0.0000,0.839010,-7.5619,-6.0612,-4.5523,NaN,0.000000
4391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,209.462222,...,2.8153,18.2699,19.4099,8.8510,6.720436,-0.2021,-1.4567,-0.2025,NaN,0.000000

In [12]:
# dfSub = df.sample(frac=0.02, random_state=22)

# dfSub.info()

In [13]:
# dfSub.groupby(["Month"]).Month.count() / len(dfSub)

In [14]:
# df.groupby(["Month"]).Month.count() / len(df)

In [15]:
# dfSub.to_csv("Data/randomSample.csv", index=False)